web: cd PriceAlert && DJANGO_SETTINGS_MODULE=PriceAlert.settings gunicorn PriceAlert.wsgi:application --log-file -
worker: cd PriceAlert && DJANGO_SETTINGS_MODULE=PriceAlert.settings celery -A PriceAlert worker -l info
scheduler: cd PriceAlert && DJANGO_SETTINGS_MODULE=PriceAlert.settings celery -A PriceAlert beat -l info 