services:
  # Webサービス（Django）
  - type: web
    name: pricealert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python PriceAlert/manage.py collectstatic --noinput
    startCommand: cd PriceAlert && gunicorn PriceAlert.wsgi:application --log-file -
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: pricealert_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: pricealert-tpqq.onrender.com,price-alert-delta.vercel.app,127.0.0.1,localhost

  # ワーカーサービス（Celery）
  - type: worker
    name: pricealert-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd PriceAlert && celery -A PriceAlert worker -l info
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: pricealert_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pricealert-redis
          property: connectionString

  # スケジューラーサービス（Celery Beat）
  - type: worker
    name: pricealert-scheduler
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd PriceAlert && celery -A PriceAlert beat -l info
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: pricealert_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pricealert-redis
          property: connectionString

# データベース
databases:
  - name: pricealert_db
    plan: free
    databaseName: pricealert
    user: pricealert_user

# Redis
services:
  - type: redis
    name: pricealert-redis
    plan: free
    ipAllowList: [] 