# Generated by Django 5.0.4 on 2025-04-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="notification_frequency",
            field=models.CharField(default="immediately", max_length=50),
        ),
    ]
