# Generated by Django 5.0.4 on 2025-04-22 23:23

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailfrequency"),
        ("users", "0002_alter_settings_notification_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="notification_frequency",
        ),
        migrations.AddField(
            model_name="settings",
            name="email_frequency",
            field=models.ForeignKey(
                default=users.models.get_default_email_frequency,
                on_delete=django.db.models.deletion.RESTRICT,
                to="notifications.emailfrequency",
            ),
        ),
    ]
