# Generated by Django 5.0.4 on 2025-04-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailfrequency"),
        ("users", "0002_alter_settings_notification_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="notification_frequency",
        ),
        migrations.AddField(
            model_name="settings",
            name="email_frequency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.emailfrequency",
            ),
            preserve_default=False,
        ),
    ]
