# Generated by Django 5.0.4 on 2025-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emailfrequency_interval"),
        ("users", "0003_remove_settings_notification_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="email_frequency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="notifications.emailfrequency",
            ),
        ),
    ]
