# Generated by Django 5.0.4 on 2025-04-21 23:56

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emailfrequency_interval"),
        ("users", "0004_alter_settings_email_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="email_frequency",
            field=models.ForeignKey(
                default=users.models.get_default_email_frequency,
                on_delete=django.db.models.deletion.RESTRICT,
                to="notifications.emailfrequency",
            ),
        ),
    ]
