# Generated by Django 5.0.4 on 2025-04-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_settings_email_frequency"),
    ]

    operations = []
