# Generated by Django 5.0.4 on 2025-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productonecsite_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="effective_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="productonecsite",
            name="current_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productonecsite",
            name="current_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productonecsite",
            name="effective_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productonecsite",
            name="shipping_fee",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="price_threshold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="threshold_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
