# Generated by Django 5.0.4 on 2025-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_pricehistory_effective_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="userproduct",
                to="products.product",
            ),
        ),
    ]
