# Generated by Django 5.0.4 on 2025-04-20 12:25

from django.db import migrations, models

FREQUENCY_CHOICES = [
    ('immediately', '即時'),
    ('daily', '毎日'),
    ('weekly', '毎週'),
]
INITIAL_FREQUENCIES = [
    ('immediately', 0),
    ('daily', 1),
    ('weekly', 7),
]

# 初期データ挿入
def insert_initial_frequencies(apps, schema_editor):
    EmailFrequency = apps.get_model('notifications', 'EmailFrequency')
    EmailFrequency.objects.bulk_create([
        EmailFrequency(email_frequency=frequency[0], interval=frequency[1]) for frequency in INITIAL_FREQUENCIES
    ])

class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=FREQUENCY_CHOICES,
                        max_length=50,
                    ),
                ),
                ("interval", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(insert_initial_frequencies, reverse_code=migrations.RunPython.noop),
    ]
