# Generated by Django 5.0.4 on 2025-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailfrequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfrequency",
            name="interval",
            field=models.IntegerField(default=0),
        ),
    ]
