# Generated by Django 5.0.4 on 2025-04-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
